name: Publish blog
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: install hugo
      run: |
        go get -u github.com/gohugoio/hugo

    - name: setup public repo
      run: |
          git clone --depth 1 https://knsh14:${{ secrets.MY_GITHUB_ACCESS_TOKEN }}@github.com/knsh14/knsh14.github.io.git public

    - name: Build
      run: |
        export PATH=$PATH:`go env GOPATH`/bin
        git submodule init
        git submodule update
        hugo

    - name: Push
      run: |
        export MSG=`git log --format=%B -n 1 HEAD`
        cd public
        if [ ! `git diff --name-only` ]; then
            echo "no different with current published page."
            exit 0
        fi
        git config --local user.name "kenshi kamata"
        git config --local user.email "kenshi.kamata@gmail.com"
        git add .
        git commit -m "${MSG}"
        git push origin master

