name: Publish blog
on:
  push:
    branches:
    - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.79.0'

    - name: setup public repo
      run: |
          git clone --depth 1 https://knsh14:${{ secrets.MY_GITHUB_ACCESS_TOKEN }}@github.com/knsh14/knsh14.github.io.git public

    - name: Build
      run: |
        hugo

    - name: Push
      run: |
        export MSG=`git log --format=%B -n 1 HEAD`
        cd public
        if [ ! `git diff --name-only` ]; then
            echo "no different with current published page."
            exit 0
        fi
        git config --local user.name "kenshi kamata"
        git config --local user.email "kenshi.kamata@gmail.com"
        git add .
        git commit -m "${MSG}"
        git push origin master

